name: buildcondition
description: description:Synchronous conditional widget renderer.
version: 1.0.0
homepage: https://github.com/the-best-is-best/buildcondition

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter